version: '3'

services:
  doc-flow-api:
    build:
      context: .
      dockerfile: ./apps/doc-flow-api/Dockerfile
    ports:
      - '3000:3000'

  doc-flow-worker:
    build:
      context: .
      dockerfile: ./apps/doc-flow-worker/Dockerfile
